apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-sm-credentials
            namespace: external-secrets
            key: accessKeyId
          secretAccessKeySecretRef:
            name: aws-sm-credentials
            namespace: external-secrets
            key: secretAccessKey